# Generated by Django 4.2.15 on 2025-10-16 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LemmaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiarity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='dictionary.lemma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lemma'], name='progress_le_user_id_7b0d04_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lemmaprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lemma'), name='uniq_progress_per_user_lemma'),
        ),
    ]
