# Generated by Django 4.2.15 on 2025-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmaprogress',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
