# Generated by Django 4.2.15 on 2025-10-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(db_index=True, max_length=64)),
                ('simplified', models.CharField(db_index=True, max_length=64)),
                ('pinyin_numbers', models.CharField(db_index=True, help_text="Pinyin from CEDICT (tone numbers in brackets), e.g. 'xue2 xi2'", max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_index', models.PositiveIntegerField(default=1)),
                ('gloss', models.CharField(max_length=512)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='dictionary.lemma')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lemma',
            constraint=models.UniqueConstraint(fields=('traditional', 'simplified', 'pinyin_numbers'), name='uniq_lemma_t_s_pinyin'),
        ),
        migrations.AddIndex(
            model_name='sense',
            index=models.Index(fields=['lemma', 'sense_index'], name='dictionary__lemma_i_87c2d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='sense',
            constraint=models.UniqueConstraint(fields=('lemma', 'sense_index'), name='uniq_sense_per_lemma_index'),
        ),
    ]
