# Generated by Django 4.2.15 on 2025-11-22 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLemmaExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_examples', to='dictionary.lemma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_examples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userlemmaexample',
            constraint=models.UniqueConstraint(fields=('user', 'lemma'), name='uniq_user_lemma_examples'),
        ),
    ]
