# Generated by Django 4.2.15 on 2025-11-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_userlemmaexample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(db_index=True, max_length=1, unique=True)),
                ('stroke_count', models.PositiveIntegerField(blank=True, null=True)),
                ('radical', models.CharField(blank=True, max_length=10, null=True)),
                ('base_meaning', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LemmaCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('specific_pinyin', models.CharField(blank=True, default='', max_length=32)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_occurrences', to='dictionary.character')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_components', to='dictionary.lemma')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='lemma',
            name='characters',
            field=models.ManyToManyField(related_name='lemmas', through='dictionary.LemmaCharacter', to='dictionary.character'),
        ),
        migrations.AddConstraint(
            model_name='lemmacharacter',
            constraint=models.UniqueConstraint(fields=('lemma', 'order_index'), name='uniq_char_position_in_lemma'),
        ),
    ]
