# Generated by Django 4.2.15 on 2025-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_character_lemmacharacter_lemma_characters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kangxi_number', models.PositiveIntegerField(help_text='The standard Kangxi dictionary number (1-214)', unique=True)),
                ('character', models.CharField(db_index=True, max_length=1)),
                ('pinyin', models.CharField(max_length=32)),
                ('english', models.CharField(max_length=128)),
                ('stroke_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['kangxi_number'],
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='radical',
        ),
        migrations.AddField(
            model_name='character',
            name='radicals',
            field=models.ManyToManyField(blank=True, related_name='characters', to='dictionary.radical'),
        ),
    ]
