# Generated by Django 4.2.15 on 2025-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_radical_remove_character_radical_character_radicals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='base_meaning',
        ),
        migrations.AddField(
            model_name='character',
            name='decomposition',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='etymology',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
