# Generated by Django 4.2.15 on 2025-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_remove_character_base_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='variants',
            field=models.JSONField(default=list, help_text='List of variant forms of this radical, stored as JSON array'),
        ),
    ]
