# Generated by Django 4.2.15 on 2025-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_radical_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radical',
            options={'ordering': ['kangxi_number'], 'verbose_name': 'Kangxi Radical'},
        ),
        migrations.RemoveField(
            model_name='radical',
            name='id',
        ),
        migrations.AddField(
            model_name='radical',
            name='frequency',
            field=models.PositiveIntegerField(default=0, help_text='Number of Chinese characters listed under this radical'),
        ),
        migrations.AddField(
            model_name='radical',
            name='simplified_character',
            field=models.CharField(blank=True, db_index=True, help_text='The simplified Chinese form', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='radical',
            name='traditional_character',
            field=models.CharField(blank=True, db_index=True, help_text='The traditional/Kangxi base form', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='radical',
            name='character',
            field=models.CharField(db_index=True, help_text='Primary display character (Simplified if available, else Traditional)', max_length=1),
        ),
        migrations.AlterField(
            model_name='radical',
            name='kangxi_number',
            field=models.PositiveSmallIntegerField(help_text='The standard Kangxi dictionary number (1-214)', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='radical',
            name='stroke_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='radical',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text="List of variant forms (e.g., ['亻', '𠆢'])"),
        ),
    ]
