# Generated by Django 4.2.15 on 2025-11-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_alter_radical_options_remove_radical_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='name_pinyin',
            field=models.CharField(blank=True, help_text="Pinyin for the colloquial name (e.g., 'yán zì páng')", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='radical',
            name='name_simplified',
            field=models.CharField(blank=True, help_text="The colloquial name (e.g., '言字旁' or '宝盖头')", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='simplified',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='radical',
            name='pinyin',
            field=models.CharField(help_text="Pinyin for the character itself (e.g., 'yán')", max_length=32),
        ),
    ]
