# Generated by Django 4.2.15 on 2025-11-29 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_radical_name_pinyin_radical_name_simplified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='radicals',
        ),
        migrations.AddField(
            model_name='character',
            name='main_radical',
            field=models.ForeignKey(blank=True, help_text='The main radical used to classify this character', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_radical', to='dictionary.radical'),
        ),
        migrations.AddField(
            model_name='character',
            name='other_radicals',
            field=models.ManyToManyField(blank=True, help_text='Additional radicals present in the graphical form of this character', related_name='other_radicals', to='dictionary.radical'),
        ),
    ]
