"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os



BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development')

if ENVIRONMENT == 'development':
    load_dotenv(os.path.join(BASE_DIR, '.env.development'))
elif ENVIRONMENT == 'production':
    load_dotenv(os.path.join(BASE_DIR, '.env.production'))


DEFAULT_API_VERSION = os.getenv('DEFAULT_API_VERSION', 'v1')
REFRESH_TOKEN_COOKIE_SECURE = os.getenv('REFRESH_TOKEN_COOKIE_SECURE', 'true').lower() in ('true', '1', 'yes', 'on')
LLM_PROVIDER = os.getenv('LLM_PROVIDER', 'openai')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_DEFAULT_MODEL = os.getenv('OPENAI_DEFAULT_MODEL', 'gpt-4o')
OPENAI_API_BASE = os.getenv('OPENAI_API_BASE', 'https://api.openai.com/v1')
LLM_TIMEOUT = int(os.getenv('LLM_TIMEOUT', '30'))
_google_redirects = os.getenv('GOOGLE_OAUTH_ALLOWED_REDIRECTS', 'postmessage')
GOOGLE_OAUTH_ALLOWED_REDIRECTS = [uri.strip() for uri in _google_redirects.split(',') if uri.strip()]
if not GOOGLE_OAUTH_ALLOWED_REDIRECTS:
    GOOGLE_OAUTH_ALLOWED_REDIRECTS = ['postmessage']
GOOGLE_OAUTH_DEFAULT_REDIRECT_URI = os.getenv(
    'GOOGLE_OAUTH_DEFAULT_REDIRECT_URI',
    GOOGLE_OAUTH_ALLOWED_REDIRECTS[0],
)
GOOGLE_OAUTH_TOKEN_TIMEOUT = int(os.getenv('GOOGLE_OAUTH_TOKEN_TIMEOUT', '10'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Ensure canonical trailing-slash URLs and redirects
APPEND_SLASH = True

_DEFAULT_ALLOWED = '127.0.0.1,localhost,[::1],testserver'
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', _DEFAULT_ALLOWED).split(',') if h.strip()]

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'storages',
    'social_django',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'apps.accounts',
    'apps.dictionary',
    'apps.lessons',
    'apps.progress',
    'apps.media',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'VERSION_PARAM': 'version',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8083",
    "http://127.0.0.1:8083",
]


CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "Authorization"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8083",
    "http://127.0.0.1:8083",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_TARGET = os.getenv('DATABASE_TARGET', 'sqlite').lower()


def _postgres_config(prefix: str):
    """Build a Postgres config from env vars with the given prefix."""
    db_name = os.getenv(f'{prefix}_DB_NAME')
    if not db_name:
        return None
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': os.getenv(f'{prefix}_DB_USER', 'postgres'),
        'PASSWORD': os.getenv(f'{prefix}_DB_PASSWORD'),
        'HOST': os.getenv(f'{prefix}_DB_HOST', 'localhost'),
        'PORT': os.getenv(f'{prefix}_DB_PORT', '5432'),
    }


if DATABASE_TARGET in ('development', 'dev'):
    default_db = _postgres_config('DEV')
elif DATABASE_TARGET == 'local':
    default_db = _postgres_config('LOCAL')
else:
    default_db = None

if default_db:
    DATABASES = {'default': default_db}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if os.getenv('AWS_STORAGE_BUCKET_NAME'):
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_CUSTOM_DOMAIN = os.getenv(
        'AWS_S3_CUSTOM_DOMAIN',
        f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
        if AWS_S3_REGION_NAME and AWS_S3_REGION_NAME != 'us-east-1'
        else f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com',
    )
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
    'REFRESH_TOKEN_COOKIE_NAME': os.getenv('REFRESH_TOKEN_COOKIE_NAME', 'refresh_token'),
    'REFRESH_TOKEN_COOKIE_PATH': os.getenv('REFRESH_TOKEN_COOKIE_PATH', '/'),
    'REFRESH_TOKEN_COOKIE_DOMAIN': os.getenv('REFRESH_TOKEN_COOKIE_DOMAIN'),
    'REFRESH_TOKEN_COOKIE_SECURE': REFRESH_TOKEN_COOKIE_SECURE,
    'REFRESH_TOKEN_COOKIE_HTTP_ONLY': True,
    'REFRESH_TOKEN_COOKIE_SAMESITE': os.getenv('REFRESH_TOKEN_COOKIE_SAMESITE', 'None'),
}

SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_POSTGRES_JSONFIELD = False
SOCIAL_AUTH_SANITIZE_REDIRECTS = True
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['openid', 'email', 'profile']
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['id', 'email', 'verified_email', 'picture']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

DJOSER = {
    'LOGIN_FIELD': 'username',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SEND_ACTIVATION_EMAIL': False,
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': False,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': False,
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_CONFIRMATION_EMAIL': False,
    'SERIALIZERS': {
        'user_create_password_retype': f'apps.accounts.api.{DEFAULT_API_VERSION}.serializers.CustomUserCreateSerializer',
        'user_create': f'apps.accounts.api.{DEFAULT_API_VERSION}.serializers.CustomUserCreateSerializer',
        'user': f'apps.accounts.api.{DEFAULT_API_VERSION}.serializers.CustomUserSerializer',
        'current_user': f'apps.accounts.api.{DEFAULT_API_VERSION}.serializers.CustomUserSerializer',
    },
}
