# Generated by Django 4.2.15 on 2025-11-27 03:13

import apps.lessons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_userlemmaexample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_language', models.CharField(default='zh', max_length=16)),
                ('target_language', models.CharField(default='en', max_length=16)),
                ('audio_url', models.URLField(blank=True, default='')),
                ('has_video_frames', models.BooleanField(default=False, help_text='True when at least one frame image has been generated')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='1-based index within lesson')),
                ('text', models.TextField()),
                ('start_char', models.PositiveIntegerField(default=0)),
                ('end_char', models.PositiveIntegerField(default=0)),
                ('start_ms', models.PositiveIntegerField(blank=True, help_text='Start time in ms (optional)', null=True)),
                ('end_ms', models.PositiveIntegerField(blank=True, help_text='End time in ms (optional)', null=True)),
                ('frame_image', models.ImageField(blank=True, help_text='Preview extracted from video', null=True, upload_to=apps.lessons.models.sentence_frame_upload_path)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SentenceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='1-based index within sentence')),
                ('text', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('word', 'Word'), ('punct', 'Punctuation'), ('latin', 'Latin'), ('space', 'Space'), ('number', 'Number')], default='word', max_length=16)),
                ('lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='dictionary.lemma')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='lessons.sentence')),
            ],
            options={
                'ordering': ['sentence_id', 'index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.sourcetext'),
        ),
        migrations.CreateModel(
            name='LessonVideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to=apps.lessons.models.lesson_video_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('total_frames', models.PositiveIntegerField(default=0)),
                ('processed_frames', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='lessons.lesson')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_pinyin', models.BooleanField(default=True)),
                ('show_pinyin_only_for_unfamiliar', models.BooleanField(default=False)),
                ('character_size', models.PositiveSmallIntegerField(default=28)),
                ('pinyin_size', models.PositiveSmallIntegerField(default=14)),
                ('show_frame_images', models.BooleanField(default=False)),
                ('autoplay_audio_on_next', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=16)),
                ('text', models.TextField()),
                ('source', models.CharField(default='user', help_text='user|machine|ingest', max_length=32)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.sentence')),
            ],
            options={
                'indexes': [models.Index(fields=['sentence', 'language'], name='lessons_sen_sentenc_fdefd7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sentencetranslation',
            constraint=models.UniqueConstraint(fields=('sentence', 'language', 'source'), name='uniq_translation_per_sentence_lang_src'),
        ),
        migrations.AddIndex(
            model_name='sentencetoken',
            index=models.Index(fields=['sentence', 'index'], name='lessons_sen_sentenc_f8dba4_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['lesson', 'index'], name='lessons_sen_lesson__0b6587_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsettings',
            index=models.Index(fields=['user', 'lesson'], name='lessons_les_user_id_516b44_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonsettings',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson_settings'),
        ),
    ]
