# Generated by Django 4.2.15 on 2025-10-15 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_language', models.CharField(default='zh', max_length=16)),
                ('target_language', models.CharField(default='en', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='1-based index within lesson')),
                ('text', models.TextField()),
                ('start_char', models.PositiveIntegerField(default=0)),
                ('end_char', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SentenceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='1-based index within sentence')),
                ('text', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('word', 'Word'), ('punct', 'Punctuation'), ('latin', 'Latin'), ('space', 'Space'), ('number', 'Number')], default='word', max_length=16)),
                ('lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='dictionary.lemma')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='lessons.sentence')),
            ],
            options={
                'ordering': ['sentence_id', 'index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.sourcetext'),
        ),
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=16)),
                ('text', models.TextField()),
                ('source', models.CharField(default='user', help_text='user|machine|ingest', max_length=32)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.sentence')),
            ],
            options={
                'indexes': [models.Index(fields=['sentence', 'language'], name='lessons_sen_sentenc_fdefd7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sentencetranslation',
            constraint=models.UniqueConstraint(fields=('sentence', 'language', 'source'), name='uniq_translation_per_sentence_lang_src'),
        ),
        migrations.AddIndex(
            model_name='sentencetoken',
            index=models.Index(fields=['sentence', 'index'], name='lessons_sen_sentenc_f8dba4_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['lesson', 'index'], name='lessons_sen_lesson__0b6587_idx'),
        ),
    ]
