# Generated by Django 4.2.15 on 2025-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='end_ms',
            field=models.PositiveIntegerField(default=0, help_text='End time in ms'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='start_ms',
            field=models.PositiveIntegerField(default=0, help_text='Start time in ms'),
        ),
    ]
