# Generated by Django 4.2.15 on 2025-10-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_sentence_end_ms_sentence_start_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='end_ms',
            field=models.PositiveIntegerField(blank=True, help_text='End time in ms (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='start_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Start time in ms (optional)', null=True),
        ),
    ]
