# Generated by Django 4.2.15 on 2025-10-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_sentence_end_ms_alter_sentence_start_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
