# Generated by Django 4.2.15 on 2025-11-18 02:47

import apps.lessons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_lesson_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='frame_image',
            field=models.ImageField(blank=True, help_text='Preview extracted from video', null=True, upload_to=apps.lessons.models.sentence_frame_upload_path),
        ),
        migrations.CreateModel(
            name='LessonVideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to=apps.lessons.models.lesson_video_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('total_frames', models.PositiveIntegerField(default=0)),
                ('processed_frames', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='lessons.lesson')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
