# Generated by Django 4.2.15 on 2025-11-19 01:53

from django.db import migrations, models


def populate_has_video_frames(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    Sentence = apps.get_model("lessons", "Sentence")
    lesson_ids = (
        Sentence.objects.exclude(frame_image="")
        .exclude(frame_image__isnull=True)
        .values_list("lesson_id", flat=True)
        .distinct()
    )
    if lesson_ids:
        Lesson.objects.filter(id__in=list(lesson_ids)).update(has_video_frames=True)


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_sentence_frame_image_lessonvideojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_video_frames',
            field=models.BooleanField(default=False, help_text='True when at least one frame image has been generated'),
        ),
        migrations.RunPython(populate_has_video_frames, migrations.RunPython.noop),
    ]
