# Generated by Django 4.2.15 on 2025-11-24 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0007_lesson_has_video_frames'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_pinyin', models.BooleanField(default=True)),
                ('show_pinyin_only_for_unfamiliar', models.BooleanField(default=False)),
                ('character_size', models.PositiveSmallIntegerField(default=28)),
                ('pinyin_size', models.PositiveSmallIntegerField(default=14)),
                ('show_frame_images', models.BooleanField(default=False)),
                ('autoplay_audio_on_next', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lesson'], name='lessons_les_user_id_516b44_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lessonsettings',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson_settings'),
        ),
    ]
